//
//  TileImages.swift
//  Tiles
//
//  Created by Norberto Taveras on 6/8/21.
//

import Foundation

class TileImages {
    public static let nameList: [String] = [
        "buttons facebook.png",
        "signs public.png",
        "tools saw.png",
        "misc books.png",
        "signs thumbsdown.png",
        "misc first aid kit.png",
        "food grape.png",
        "magic empty rounded flask.png",
        "misc game achievements.png",
        "casino party on.png",
        "weapons medieval sword.png",
        "misc space rocket.png",
        "buttons feed.png",
        "military piercing ammo.png",
        "drawing eraser.png",
        "buttons cancel.png",
        "music megaphone.png",
        "construction column.png",
        "drawing pen.png",
        "chess white horse.png",
        "misc game missions.png",
        "tools wrench.png",
        "music piano.png",
        "misc calendar.png",
        "misc folder1.png",
        "music radio.png",
        "emoticons happy.png",
        "emoticons crush.png",
        "monster zombie hand.png",
        "food banana.png",
        "tools screwdriver.png",
        "signs thumbsup.png",
        "military helmet.png",
        "toggle lightbulb on.png",
        "weapons gaunlets.png",
        "tools shovel.png",
        "misc folder2.png",
        "misc credit card.png",
        "emoticons confused.png",
        "music treble clef.png",
        "magic ripped eye.png",
        "music microphone.png",
        "construction asphalt.png",
        "powerups super jump.png",
        "food garlic.png",
        "casino dice.png",
        "monetary gold coins.png",
        "food corn.png",
        "monetary treasure open.png",
        "minerals blue.png",
        "misc chat.png",
        "dressup skirt.png",
        "emoticons glasses.png",
        "magic wizard hat.png",
        "emoticons little kiss.png",
        "signs stop.png",
        "misc box.png",
        "buttons skip.png",
        "weapons katana.png",
        "monster zombie1.png",
        "tools swiss knife.png",
        "drawing eyedropper.png",
        "buttons add.png",
        "minerals coal.png",
        "minerals rock.png",
        "powerups magnet.png",
        "food pumpkin.png",
        "emoticons crying.png",
        "farm tree.png",
        "tools rope.png",
        "drawing colors.png",
        "monster zombie2.png",
        "magic triangle flask.png",
        "toggle lightbulb off.png",
        "food mushroom.png",
        "construction helmet.png",
        "casino horse shoe.png",
        "construction earth.png",
        "magicempty bulb flask.png",
        "monster brain.png",
        "food pork thig.png",
        "military truck.png",
        "food pineapple.png",
        "monetary vault.png",
        "military chainsaw.png",
        "emoticons crying out loud.png",
        "magic bone.png",
        "chess black pawn.png",
        "military strategy.png",
        "minerals green stone.png",
        "elements fire.png",
        "emoticons laughing out loud.png",
        "emoticons broken heart.png",
        "magic grave.png",
        "minerals red stone.png",
        "tools torch.png",
        "dressup brush.png",
        "military knife.png",
        "casino token.png",
        "misc game coop.png",
        "toggle music off.png",
        "magic cylinder flask.png",
        "dressup eye.png",
        "misc game combat.png",
        "military machine gun.png",
        "dressup brows.png",
        "music speaker.png",
        "monetary wallet.png",
        "magic empty square flask.png",
        "misc exit door.png",
        "misc game leaderboards1.png",
        "misc company.png",
        "misc camera.png",
        "food lemon.png",
        "misc book.png",
        "misc game life.png",
        "monetary treasure closed.png",
        "misc disc.png",
        "dressup lipstick.png",
        "dressup earrings.png",
        "drawing large brush.png",
        "monetary gold coin.png",
        "dressup wash.png",
        "dressup ear.png",
        "minerals pure gold.png",
        "buttons share.png",
        "monetary gold bars.png",
        "buttons do.png",
        "tutorial direction asdw.png",
        "toggle music on.png",
        "magic bulb flask.png",
        "magic cauldron.png",
        "weapons sledgehammer.png",
        "music headphone.png",
        "weapons medieval helmet.png",
        "dressup lips.png",
        "signs rock on.png",
        "weapons wood shield.png",
        "weapons spear.png",
        "misc file.png",
        "buttons upload upgrade.png",
        "emoticons good.png",
        "construction bricks.png",
        "dressup ring.png",
        "minerals blue stone.png",
        "buttons remove.png",
        "misc game multiplayer.png",
        "signs hi5.png",
        "military pistol.png",
        "dressup feminine shoe.png"
    ]
}
